[package]
name = "integration-test"
version = "0.1.0"
edition = "2021"

[dependencies]
omni-director = { path = "../OmniDirector" }
omni-event-registry = { path = "../shared/event-registry" }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"