[package]
name = "vm-management-feature"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
omni-ffi-macros = { path = "../../shared/ffi-macros" }
serde_json = "1.0"