[workspace]
members = ["crates/*"]
 # To interact with the MegaTrix section of the project you will have to either
 # use the makefile-defined commands, or run the cargo commands manually in the
 # crates/MegaTrix directory
exclude = [
    "crates/MegaTrix",
    "crates/features",
    "crates/providers", 
    "crates/shared"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tristan Poland"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/OmniCloudOrg/OmniCloud-Full"
description = "OmniCloud project workspace"

[workspace.dependencies]
# WE DO NOT USE WORKSPACE DEPENDENCIES OTHER THAN LibOmni, THIS BREAKS THE
# INDIVIDUAL REPOS ABILITY TO RUN INDEPENDENTLY OF THE WORKSPACE OTHERWISE.