services:
  agent:
    build:
      context: ../crates/OmniAgent/
      dockerfile: ./Dockerfile
    ports:
      - "5670:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  orchestrator:
    build:
      context: ../crates/OmniOrchestrator/
      dockerfile: ./Dockerfile
    ports:
      - "5671:8002"
    environment:
      - NODE_ENV=development
      - DEFAULT_DATABASE_URL=mysql://root:root@orchestrator_db:3306/omni
      - OMNI_ORCH_BYPASS_CONFIRM=confirm
    networks:
      - omni_network

  orchestrator_db:
    container_name: Omni_DB_New
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omni
    ports:
      - "4001:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - omni_network

  forge:
    build:
      context: ../crates/OmniForge/
      dockerfile: ./Dockerfile
    ports:
      - "5672:8080"
    environment:
      - NODE_ENV=development

  cosmos:
    build:
      context: ../services/OmniCosmos/
      dockerfile: ./Dockerfile
    ports:
      - "5673:3000"
    environment:
      - NODE_ENV=development

#  editor:
#    build:
#      context: ../services/OmniEditor/
#      dockerfile: ./Dockerfile
#    ports:
#      - "5674:8080"
#    environment:
#      - NODE_ENV=development

  director:
    build:
      context: ../crates/OmniDirector/
      dockerfile: ./Dockerfile
    ports:
      - "5675:8081"
    environment:
      - NODE_ENV=development

volumes:
  db_data:

networks:
  omni_network: