services:
  agent:
    build:
      context: ../crates/OmniAgent/
      dockerfile: ./Dockerfile
    ports:
      - "5670:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  orchestrator:
    build:
      context: ../crates/OmniOrchestrator/
      dockerfile: ./Dockerfile
    ports:
      - "5671:8002"
    environment:
      - NODE_ENV=development
      - DEFAULT_DATABASE_URL=mysql://root:root@orchestrator_db:3306/omni
      - OMNI_ORCH_BYPASS_CONFIRM=confirm
    networks:
      - omni_network

  orchestrator_db:
    container_name: Omni_DB_New
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omni
    ports:
      - "4001:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - omni_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native ClickHouse protocol
      - "8090:8080" # HTTP interface for ClickHouse
    volumes:
      - clickhouse-data:/var/lib/clickhouse:rw
      - clickhouse-logs:/var/log/clickhouse-server:rw
      - ./clickhouse-config:/etc/clickhouse-server/config.d:rw
      - ./clickhouse-users:/etc/clickhouse-server/users.d:rw
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=your_secure_password
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - omni_network

  forge:
    build:
      context: ../crates/OmniForge/
      dockerfile: ./Dockerfile
    ports:
      - "5672:8080"
    environment:
      - NODE_ENV=development

  cosmos:
    build:
      context: ../services/OmniCosmos/
      dockerfile: ./Dockerfile
    ports:
      - "5673:3000"
    environment:
      - NODE_ENV=development

#  editor:
#    build:
#      context: ../services/OmniEditor/
#      dockerfile: ./Dockerfile
#    ports:
#      - "5674:8080"
#    environment:
#      - NODE_ENV=development

  director:
    build:
      context: ../crates/OmniDirector/
      dockerfile: ./Dockerfile
    ports:
      - "5675:8081"
    environment:
      - NODE_ENV=development

volumes:
  db_data:
  clickhouse-data:
  clickhouse-logs:

networks:
  omni_network: